name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install

    - name: Build and Push Docker Image
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: salesjoep/post-ms:v1
        
      #login
    - name: Azure Login
      uses: Azure/login@v1.4.4
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_TOKEN }}
    - run: |
        az group list
        
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v2.1
      with:
        # Resource Group Name
        resource-group: social-it
        # AKS Cluster Name
        cluster-name: socialitcluster
        
    - name: Create secret in Kubernetes cluster
      uses: Azure/k8s-create-secret@v2.1
      with:
        container-registry-url: https://index.docker.io/v2/
        container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
        container-registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Type of Kubernetes secret. For example, docker-registry or generic
        secret-type: docker-registry
        # Name of the secret. You can use this secret name in the Kubernetes YAML configuration file.
        secret-name: docker-image-pull-secret
               
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v3.1
      with:
        # Path to the manifest files which will be used for deployment.
        manifests: depl/post-depl.yaml
        # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
        images: salesjoep/post-ms:v1
        # Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files
        imagepullsecrets: docker-image-pull-secret
        # Switch whether to pull the images from the registry before deployment to find out Dockerfile's path in order to add it to the annotations
        action: deploy
